local builtin = require('telescope.builtin')

vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>cs', builtin.colorscheme, {})
vim.keymap.set('n', '/', builtin.current_buffer_fuzzy_find, {})
vim.keymap.set('n', '<leader>gbc', builtin.git_bcommits, {})
vim.keymap.set('v', '<leader>gbc', builtin.git_bcommits_range, {})
vim.keymap.set('n', '<leader>gbl', builtin.git_branches, {})
vim.keymap.set('n', '<leader>gbb', '<cmd>:G blame<cr>')
vim.keymap.set('n', '<leader>lds', builtin.lsp_document_symbols, {})
vim.keymap.set('n', '<leader>todo', '<cmd>:TodoTelescope<cr>')
